# This config file is a dummy CircleCI config that does nothing. We migrated away from CircleCI to Github Actions.
# But our release/0.10 branch still uses CircleCI, so we can't disable the service entirely and need some way
# to disable it only for newer versions. That's what this file is doing.

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:11.12.0
    steps:
      - run:
          name: Dummy
          command: 'echo Not running any Circle CI'
